export const CASES = {
    GET_ALL: "GET_ALL",
    GET_NAME: "GET_NAME",
    GET_DETAIL_ID: "GET_DETAIL_ID",
    GET_TEMPERAMENT: "GET_TEMPERAMENT",
    BY_TEMPERAMENT: 'BY_TEMPERAMENT',
    BY_CREATED: 'BY_CREATED',
    BY_ORDER: "BY_ORDER",
    BY_ORDER_WEIGHT: "BY_ORDER_WEIGHT",
    CLEAR_DETAIL: "CLEAR_DETAIL"
}